
var getTimezoneByAbbreviation = function(abbr)
{
    for(var i=0; i< timezones.length; i++)
        {
            if (timezones[i][1] == abbr) {
                return timezones[i][0];
            }
        }
        return null;
}

var timezones = [
        //offset, abbr, name, standard (if DST)
        [0, 'UTC', 'Coordinated Universal Time'],
        [0, 'GMT', 'Greenwich Mean Time'],
        [0, 'UK', 'United Kingdom'],
        [+1, 'ES', 'Spain'],
        //north america
        [-1, 'EGT', 'East Greenland Time'],
        [-3, 'WGT', 'West Greenland Time'],
        [-3, 'PMST', 'Pierre & Miquelon Standard Time'],
        [-3.5, 'NST', 'Newfoundland Standard Time'],
        [-4, 'AST', 'Atlantic Standard Time'],
        [-5, 'EST', 'Eastern Standard Time'],
        [-6, 'CST', 'Central Standard Time'],
        [-7, 'MST', 'Mountain Standard Time'],
        [-8, 'PST', 'Pacific Standard Time'],
        [-9, 'AKST', 'Alaska Standard Time'],
        [-10, 'HAST', 'Hawaii-Aleutian Standard Time'],
        [0, 'EGST', 'Eastern Greenland Summer Time', '-1:EGT'],
        [-2, 'WGST', 'Western Greenland Summer Time', '-3:WGT'],
        [-2, 'PMDT', 'Pierre & Miquelon Daylight Time', '-3:PMST'],
        [-2.5, 'NDT', 'Newfoundland Daylight Time', '-3.5:NST'],
        [-3, 'ADT', 'Atlantic Daylight Time', '-4:AST'],
        [-4, 'EDT', 'Eastern Daylight Time', '-5:EST'],
        [-5, 'CDT', 'Central Daylight Time', '-6:CST'],
        [-6, 'MDT', 'Mountain Daylight Time', '-7:MST'],
        [-7, 'PDT', 'Pacific Daylight Time', '-8:PST'],
        [-8, 'AKDT', 'Alaska Daylight Time', '-9:AKST'],
        [-9, 'HADT', 'Hawaii-Aleutian Daylight Time', '-10:HAST'],
        [-5, 'CST', 'Cuba Standard Time'],
        [-4, 'CDT', 'Cuba Daylight Time', '-5:CST'],
        //south america
        [-4, 'AMT', 'Amazon Time'],
        [-3, 'AMST', 'Amazon Summer Time', '-4:AMT'],
        [-3, 'ART', 'Argentina Time'],
        [-4, 'BOT', 'Bolivia Time'],
        [-3, 'BRT', 'Brasilia Time'],
        [-2, 'BRST', 'Brasilia Summer Time', '-3:BRT'],
        [-4, 'CLT', 'Chile Standard Time'],
        [-3, 'CLST', 'Chile Summer Time', '-4:CLT'],
        [-5, 'COT', 'Columbia Time'],
        [-5, 'ECT', 'Ecuador Time'],
        [-4, 'FKT', 'Falkland Islands Time'],
        [-3, 'FKST', 'Falkland Islands Summer Time', '-4:FKT'],
        [-2, 'FNT', 'Fernando de Noronha Time'],
        [-3, 'GFT', 'French Guiana Time'],
        [-4, 'GYT', 'Guyana Time'],
        [-5, 'PET', 'Peru Time'],
        [-4, 'PYT', 'Paraguay Time'],
        [-3, 'PYST', 'Paraguay Summer Time', '-4:PYT'],
        [-3, 'SRT', 'Suriname Time'],
        [-3, 'UYT', 'Uruguay Time'],
        [-2, 'UYST', 'Uruguay Summer Time', '-3:UYT'],
        [-4.5, 'VET', 'Venezuelan Standard Time'],
        //africa
        [2, 'CAT', 'Central Africa Time'],
        [-1, 'CVT', 'Cape Verde Time'],
        [3, 'EAT', 'Eastern Africa Time'],
        [4, 'MUT', 'Mauritius Time'],
        [4, 'RET', 'Reunion Time'],
        [2, 'SAST', 'South Africa Standard Time'],
        [4, 'SCT', 'Seychelles Time'],
        [1, 'WAT', 'West Africa Time'],
        [2, 'WAST', 'West Africa Summer Time', '1:WAT'],
        [0, 'WT', 'Western Sahara Standard Time'],
        //europe
        [1, 'BST', 'British Summer Time', '0:GMT'],
        [1, 'CET', 'Central European Time'],
        [2, 'CEST', 'Central European Summer Time', '1:CET'],
        [2, 'EET', 'Eastern European Time'],
        [3, 'EEST', 'Eastern European Summer Time', '2:EET'],
        [0, 'WET', 'Western European Time'],
        [1, 'WEST', 'Western European Summer Time', '0:WET'],
        [1, 'IST', 'Irish Standard Time', '0:GMT'],
        [1, 'IST (Ireland)', 'Irish Standard Time', '0:GMT'],
             [8, 'SGT', 'Singapore Time'],
        [5, 'TJT', 'Tajikistan Time'],
        [9, 'TLT', 'East Timor Time'],
        [5,'TMT','Turkmenistan Time'],
        [8,'ULAT','Ulaanbaatar Time'],
        [5,'UZT','Uzbekistan Time'],
        [10,'VLAT','Vladivostok Time'],
        [11,'VLAST','Vladivostok Summer Time', '10:VLAT'],
        [7,'WIB','Western Indonesian Time'],
        [9,'WIT','Eastern Indonesian Time'],
        [8,'WITA','Central Indonesian Time'],
        [9,'YAKT','Yakutsk Time'],
        [10,'YAKST','Yakutsk Summer Time', '9:YAKT'],
        [5,'YEKT','Yekaterinburg Time'],
        [6,'YEKST','Yekaterinburg Summer Time', '5:YEKT'],
        //pacific
        [12.75, 'CHAST','Chatham Island Standard Time'],
        [13.75, 'CHADT','Chatham Island Daylight Time', '12.75:CHAST'],
        [10, 'ChST','Chamorro Standard Time'],
        [-10, 'CKT','Cook Island Time'],
        [-6, 'EAST','Easter Island Standard Time'],
        [-5, 'EASST','Easter Island Summer Time', '-6:EAST'],
        [11, 'EDT','Eastern Daylight Time'],
        [13, 'FJST','Fiji Summer Time'],
        [12, 'FJT','Fiji Time'],
        [-6, 'GALT','Galapagos Time'],
        [-9, 'GAMT','Gambier Time'],
        [12, 'GILT','Gilbert Island Time'],
        [14, 'LINT','Line Islands Time'],
        [-9.5, 'MART','Marquesas Time'],
        [12, 'MHT','Marshall Islands Time'],
        [11, 'NCT','New Caledonia Time'],
        [-11, 'NUT','Niue Time'],
        [12, 'NZST','New Zealand Standard Time'],
        [13, 'NZDT','New Zealand Daylight Time', '12:NZST'],
        [10, 'PGT','Papua New Guinea Time'],
        [13, 'PHOT','Phoenix Island Time'],
        [11, 'PONT','Pohnpei Standard Time'],
        [-8, 'PST','Pitcairn Standard Time'],
        [9, 'PWT','Palau Time'],
        [11, 'SBT','Solomon Islands Time'],
        [-11, 'SST','Samoa Standard Time'],
        [-10, 'TAHT','Tahiti Time'],
   [4, 'KUYT', 'Kuybyshev Time'],
        [4, 'SAMT', 'Samara Time', '4:KUYT'],
        [3, 'MSK', 'Moscow Standard Time'],
        [4, 'MSD', 'Moscow Daylight Time', '3:MSK'],
        //asia
        [4.5, 'AFT', 'Afghanistan Time'],
        [6, 'ALMT', 'Alma-Ata Time'],
        [4, 'AMT', 'Armenia Time'],
        [5, 'AMST', 'Armenia Summer Time', '4:AMT'],
        [12, 'ANAT', 'Anadyr Time'],
        [12, 'ANAST', 'Anadyr Summer Time', '12:ANAT'],
        [5, 'AQTT', 'Aqtobe Time'],
        [3, 'AST', 'Arabia Standard Time'],
        [4, 'AZT', 'Azerbaijan Time'],
        [5, 'AZST', 'Azerbaijan Summer Time', '4:AZT'],
        [8, 'BNT', 'Brunei Darussalam Time'],
        [6, 'BST', 'Bangladesh Standard Time'],
        [6, 'BTT', 'Bhutan Time'],
        [8, 'CST', 'China Standard Time'],
        [4, 'GET', 'Gerogia Standard Time'],
        [4, 'GST', 'Gulf Standard Time'],
        [8, 'HKT', 'Hong Kong Time'],
        [7, 'HOVT', 'Hovd Time'],
        [7, 'ICT', 'Indochina Time'],
        [2, 'IST', 'Israel Standard Time'],
        [2, 'IST (Israel)', 'Israel Standard Time'],
        [3, 'IDT', 'Israel Daylight Time', '2:IST'],
        [5.5, 'IST', 'India Standard Time'],
        [3.5, 'IRST', 'Iran Standard Time'],
        [4.5, 'IRDT', 'Iran Daylight Time', '3.5:IRST'],
        [8, 'IRKT', 'Irkutsk Time'],
        [9, 'IRKST', 'Irkutsk Summer Time'],
        [9, 'JST', 'Japan Standard Time'],
        [6, 'KGT', 'Kyrgyzstan Time'],
        [7, 'KRAT', 'Krasnoyarsk Time'],
        [8, 'KRAST', 'Krasnoyarsk Summer Time', '7:KRAT'],
        [9, 'KST', 'Korea Standard Time'],
        [11, 'MAGT', 'Magadan Time'],
        [12, 'MAGST', 'Magadan Summer Time', '11:MAGT'],
        [6.5, 'MMT', 'Myanmar Time'],
        [5, 'MVT', 'Maldives Time'],
        [8, 'MYT', 'Malaysia Time'],
        [6, 'NOVT', 'Novosibirsk Time'],
        [7, 'NOVST', 'Novosibirsk Summer Time', '6:NOVT'],
        [5.75, 'NPT', 'Nepal Time'],
        [6, 'OMST', 'Omsk Standard Time'],
        [7, 'OMSST', 'Omsk Summer Time'],
        [12, 'PETT', 'Kamchatka Time'],
        [12, 'PETST', 'Kamchatka Summer Time'],
        [8, 'PHT', 'Philippine Time'],
        [5, 'PKT', 'Pakistan Standard Time'],
        [-10, 'TKT','Tokelau Time'],
        [12, 'TVT','Tuvalu Time'],
        [11, 'VUT','Vanuatu Time'],
        [12, 'WFT','Wallis and Futuna Time'],
        [-11, 'WST','West Samoa Time'],
        [10, 'YAPT','Yap Time'],
        //australia
        [9.5, 'CST', 'Central Standard Time'],
        [9.5, 'CST (Australia)', 'Central Standard Time'],
        [10.5, 'CDT', 'Central Daylight Time', '9.5:CST'],
        [7, 'CXT', 'Christmas Island Time'],
        [10, 'EST', 'Eastern Standard Time'],
        [10, 'EST (Australia)', 'Eastern Standard Time'],
        [11, 'EDT', 'Eastern Daylight Time', '10:EST'],
        [10.5, 'LHST', 'Lord Howe Standard Time'],
        [11, 'LHDT', 'Lord Howe Daylight Time', '10.5:LHST'],
        [11.5, 'NFT', 'Norfolk Time'],
        [8, 'WST', 'Western Standard Time'],
        [9, 'WDT', 'Western Daylight Time', '8:WST'],
        //misc
        [-1, 'AZOT', 'Azores Time'],
        [0, 'AZOST', 'Azores Summer Time', '-1:AZOT'],
        [6.5, 'CCT', 'Cocos Islands Time'],
        [6, 'IOT', 'Indian Chagos Time'],
        [5, 'TFT', 'French Southern and Artarctic Time'],
        [8, 'CAST', 'Casey Time'],
        [7, 'DAVT', 'Davis Time'],
        [5, 'MAWT', 'Mawson Time']
        ];