window.handlerbet365={bookieName:"bet365",fileName:"bet365.js",objName:"handlerbet365",URLmatchstring:"bet365.com",bookieURL:"https://mobile.bet365.com/premium",checkBetSlipAddedInterval:300,checkBetSlipAddedMaxCounter:50,checkBetSlipClearedInterval:301,checkBetSlipClearedMaxCounter:50,checkPageLoadedInterval:300,checkPageLoadedMaxCounter:50,sc:150,bet:null,username:"",password:"",mainPageLoadCounter:0,loginPageLoadCounter:0,betPageLoadCounter:0,loginNavigationPageLoadCounter:0,balancePageLoadCounter:0,
j:!0,checkAreWeOnBookiesPage:function(a){return a.domain&&0<=a.domain.toString().indexOf("bet365")?!0:!1},checkAreWeOnBetPage:function(a,c){try{if(a){var b=a.querySelector(".MiscBoxContent");if(b&&0<=b.innerHTML.indexOf("This page is no longer available"))throw Error(bfMisc.errorMessages.ERR_BET_SUSPENDED);if(0<=a.URL.indexOf("type=BetSlip"))return!1;var d=this.bet.betlink.match("GAME_LINK=(.*)")[1].match("key=[-0-9]+");if(d&&0<=a.URL.indexOf(d[0])){for(var e=this.bet.betlink.match("ORIG_MARKET_NAME=([^;]+)")[1].replace(/^\s+|\s+$/g,
"").replace("Alternative ","").toLowerCase(),g=a.querySelectorAll(".Section"),b=0;b<g.length;b++)if(0<=g[b].children[0].textContent.trim().replace("Alternative ","").toLowerCase().indexOf(e)){if("closed"==g[b].getAttribute("data-displaystate")){g[b].click();break}return!0}setTimeout(c(!0),3E3);return"_use_callback"}}return!1}catch(f){return{error:f.message,Z:f.stack}}},boolIsPageFinishedLoading:function(a,c){if(a&&a.body&&"complete"==a.readyState){try{if(!handler.bet)return!1}catch(b){}if(a.body.hasAttribute("loadingInProgress"))return!1;
if(null!==a.getElementById("ctl00_HeaderPanelMain_lbClearCancelText"))return a.getElementById("ctl00_HeaderPanelMain_lbClearCancelText").click(),!1;var d=a.getElementById("Main");if(d&&d.querySelector("#loadingInProgress")){if("beforelogin"==c){if(a.getElementById("PopUp_UserName"))return!0}else"bet"==c&&(d=a.getElementById("rw_spl_sc_99999"))&&-1==d.className.indexOf("homePageRowActive")&&d.click();return!1}var d=a.getElementById("spinnerBox"),e=a.getElementById("preLoadOuter"),g=a.querySelector(".LogInPopUpBottom input"),
f=a.getElementById("LoginFailedTxt");if("mainopened"==c&&this.isLoggedIn(a))return(d=a.getElementById("BetSlipCloseIcon"))?(d.click(),!0):(d=a.querySelector("#BigBttn.LogInPopUpBottom > input"))?(a.body.removeAttribute("popupbypassed"),a.body.removeAttribute("popupoccured"),d.click(),!0):!1;if(d)return"login"==c&&a.body.hasAttribute("loginclicked")&&(d=0,a.body.hasAttribute("spinnercounter")&&(d=a.body.getAttribute("spinnercounter")),a.body.setAttribute("spinnercounter",++d),5<=d&&(a.location=this.bookieURL)),
!1;if(e&&null!=e.getAttribute("style"))if("login"==c)if(a.body.hasAttribute("loginclicked")){if(f&&f.hasAttribute("style"))return!0;if(g)return g.click(),!1;a.location=this.bookieURL}else return!0;else{if(a.querySelector(".SctActive"))return!1;if(d=this.bet.betlink.match("ORIG_MARKET_NAME=([^;]+)")){d=d[1].replace(/^\s+|\s+$/g,"");e=a.querySelectorAll(".SctClosed span");for(g=0;g<e.length;g++)if(0<=e[g].innerHTML.indexOf(d))return!1==e[g].hasAttribute("clicked")&&(e[g].setAttribute("clicked","true"),
e[g].click()),!1;return a.querySelector(".SctActive")?!1:!0}}if("mainreused"==c)return a.getElementById("Main")||(a.location.href=this.bookieURL),!0}return!1},navigateLoginPage:function(a){var c=a.getElementById("Main");c?(a=a.createElement("div"),a.id="loadingInProgress",c.appendChild(a)):a.body.setAttribute("loadingInProgress","true");return{url:this.bookieURL+"/#type=Login;key=;ip=0;lng=1"}},navigateBetPage:function(a){var c=a.getElementById("Main");c?(a=a.createElement("div"),a.id="loadingInProgress",
c.appendChild(a)):a.body.setAttribute("loadingInProgress","true");c="";a=this.bet.betlink.match("key=([^;]+)")[1];c="try{\nvar linkDiv = document.createElement('div');\nlinkDiv.setAttribute('id', 'rw_spl_sc_99999');\n";c+="linkDiv.setAttribute('data-nav', 'rw_spl_sc_99999,CouponRow,"+a+",False,1');\n";c+="linkDiv.setAttribute('class', 'homePageRow homeRowDbl homeFeatRow');\n";c+="var mainTag = document.querySelector(\"#Main, [id*='ctl00_Main']\");";c+="mainTag.appendChild(linkDiv);\n";c+="linkDiv.click();\n";
c+="}catch(e){console.log(e)}\n";return{script:c}},checkBetSlipOpened:function(a){if(a){var c=a.querySelectorAll("#SelectionCount");if((c=2==c.length?c[1].innerHTML.trim():c[0].innerHTML.trim())&&"0"==c||a.querySelector("a[data-nav='AddToBetSlip']"))return!0}return!1},openBetSlip:function(a,c){if(a){var b=a.querySelectorAll("#SelectionCount");if("0"==(2==b.length?b[1].innerHTML.trim():b[0].innerHTML.trim()))return!0;if(b=a.getElementById("betslipBar"))return b.click(),setTimeout(c(!0),1250),"_use_callback"}return!1},
addBetSlip:function(a,c,b){if(a){c=this.c(c);console.log(c);if(a=a.querySelector(c))return a.click(),setTimeout(b(!0),1250),"_use_callback";throw Error(bfMisc.errorMessages.ERR_BET_NOT_EXISTS);}return!1},g:function(a,c){for(var b=null,d=bfMisc.Xc(a,"bs").replace("||||","||").split("||"),e=0;e<d.length-1;e++){var g=!1;c.fp&&0<=d[e].indexOf("fp="+c.fp)&&(g=!0);g&&c.ln&&-1===d[e].indexOf("ln="+c.ln)&&(g=!1);g&&c.Inc&&-1===d[e].indexOf("Inc="+c.Inc)&&(g=!1);g&&(b={index:e,str:d[e]})}return b},c:function(a){if(!a.fp||
a.ln||a.Inc){if(a.fp&&a.ln&&!a.Inc)return"[data-nav*='"+a.fp+"'][data-nav*='ln="+a.ln+"']";if(a.fp&&!a.ln&&a.Inc)return"[data-nav*='"+a.fp+"'][data-nav*='Inc="+a.Inc+"']";if(a.fp&&a.ln&&a.Inc)return"[data-nav*='"+a.fp+"'][data-nav*='ln="+a.ln+"'][data-nav*='Inc="+a.Inc+"']"}else return"[data-nav*='"+a.fp+"']";return null},checkBetSlipAdded:function(a,c,b){if(a&&"complete"==a.readyState){if(a.querySelector("a[data-nav='AddToBetSlip']"))return setTimeout(b(!0),750),"_use_callback";if((b=a.querySelector("a[data-nav='AddToBetSlip']"))||
(b=a.getElementById("BetAddedPopUpBox"))&&-1==b.getAttribute("style").indexOf("none")&&(b=a.querySelector("[data-nav='bs_goto']")))return b.click(),!1;var d=a.getElementById("overlay");c=a.querySelector(".Selected"+this.c(c));if(((b=a.querySelector(".OverlayBetSlipMessage"))||c)&&null==d&&(b=a.querySelector("#betslipBar>[data-nav='bs_goto']")))return b.click(),!1;(b=a.querySelector("#betslipBar>[data-nav='bs_goto']"))&&1==b.querySelector("#SelectionCount").textContent.trim()&&b.click()}return!1},
clearBetSlip:function(a){if(a&&(a=a.querySelector(".removeAll")))return a.click(),!0},checkBetSlipCleared:function(a){return a&&(a=a.querySelectorAll("#SelectionCount"),(a=2==a.length?a[1].innerHTML.trim():a[0].innerHTML.trim())&&"0"==a)?!0:!1},getBetData:function(a){try{this.parser.doc=a;this.parser.parent=this;this.parser.bet={};this.parser.get_bookieName();this.parser.get_betlink();this.parser.get_players();this.parser.get_market();this.parser.get_leg();this.parser.get_handicap();this.parser.get_decimalOdd();
this.parser.get_kickoff();var c=this.parser.get_betID();return{bet:this.parser.bet,betID:c}}catch(b){return{error:b.message,Z:b.stack}}},getBetSlipData:function(a,c){try{return this.betSlipParser.parent=this,this.betSlipParser.doc=a,this.betSlipParser.a={},this.betSlipParser.betID=c,this.betSlipParser.b=this.betSlipParser.get_mainTag(),this.betSlipParser.get_players(),this.betSlipParser.get_market(),this.betSlipParser.get_leg(),this.betSlipParser.get_handicap(),this.betSlipParser.get_decimalOdd(),
{bet:this.betSlipParser.a}}catch(b){return{error:b.message,Z:b.stack}}},clickLogin:function(a){if(a){var c=a.querySelector("input[data-nav='LogInUserFromPopUp']");if(c)return a.body.setAttribute("loginclicked","true"),c.click(),!0}return!1},isLoggedIn:function(a){return a&&(a=a.getElementById("NavUserBalance"))&&""!=a.innerHTML?!0:!1},fillLoginForms:function(a,c,b){try{if(a&&c&&b){if(!c.match(".+"))throw Error("Invalid username");if(!b.match(".+"))throw Error("Invalid password");a.getElementById("PopUp_UserName").value=
c;a.getElementById("PopUp_Password").value=b;return!0}return{error:"Cannot fill login information"}}catch(d){return{error:d.message,Z:d.stack}}},getBalance:function(a){var c=null,b=null,d=null;a&&(a=a.getElementById("NavUserBalance"))&&(d=a.innerHTML,(a=d.match("[\\.0-9]+"))&&(c=a[0]),0<=d.indexOf("EUR")?b="EUR":0<=d.indexOf("HUF")?b="HUF":0<=d.indexOf("RON")?b="RON":0<=d.indexOf("GBP")?b="GBP":0<=d.indexOf("USD")?b="USD":0<=d.indexOf("SEK")&&(b="SEK"));return{balance:c,currency:b,currencyStr:d}},
getMinMaxStake:function(){return{minStake:null,maxStake:null}},setAmount:function(a,c,b){if(a&&this.g(a,c)){c=a.querySelector(".stake>input");var d=a.querySelector("#BetSlipForm span.totalStake");if(c&&d)return d.innerHTML="0.00",c.focus(),c.click(),c.value=b,a=a.createEvent("KeyboardEvent"),a[(a.initKeyboardEvent||a.initKeyEvent).name]("keyup",!0,!0,null,!1,!1,!1,!1,13,0),c.dispatchEvent(a),c.blur(),!0}return!1},getTotalAmountSet:function(a){return a&&(a=a.querySelector("#BetSlipForm span.totalStake"))?
parseFloat(a.innerHTML):null},checkBet:function(a){return a&&(a=a.querySelector("input[data-nav='bs_PlaceBetEnabled']"))?(a.click(),!0):!1},checkBetPlaced:function(a){return a?!0:!1},parser:{get_bookieName:function(){this.bet.bookieName=this.parent.bet.bookieName;return this.bet.bookieName},get_market:function(){for(var a=null,c=this.get_betID(),b=this.bet.betlink.match("ORIG_MARKET_NAME=([^;]+)")[1].replace(/^\s+|\s+$/g,"").replace("Alternative ","").toLowerCase(),d=this.doc.querySelectorAll(".Section"),
e=0;e<d.length;e++)if(d[e].querySelector(this.parent.c(c))){var g=d[e].children[0].textContent.trim().replace("Alternative ","").toLowerCase();0<=g.indexOf(b)&&(a=this.parent.bet.market);break}if(null==a&&g&&(c=this.parent.betMarketToString[this.parent.bet.market]))for(e=0;e<c.length;e++)0<=g.indexOf(c[e].toLowerCase())&&(a=this.parent.bet.market);this.bet.market=a;return this.bet.market},get_betlink:function(){var a=this.parent.bet.betlink,c=this.get_betID(),b=this.doc.querySelector(this.parent.c(c));
if(!b){var d=null,e=this.parent.bet.leg,e="B1"==e||"BO"==e?0:1,g=a.match("ORIG_MARKET_NAME=([^;]+)")[1].replace(/^\s+|\s+$/g,"").replace("Alternative ",""),f=document.querySelectorAll("[data-nav*='"+c.f+"'][data-nav*='ln="+c.ln+"']");0==f.length&&(f="undefined"!=typeof c.ln?document.querySelectorAll("[data-nav*='"+c.f+"'][data-nav*='ln="+c.ln.replace(/[0]+$/g,"")+"']"):document.querySelectorAll("[data-nav*='"+c.f+"']"));for(c=0;c<f.length;c++){var h=f[c],k=0;h===h.parentNode.children[0]?k=0:h===h.parentNode.children[1]&&
(k=1);var p=h.parentNode.parentNode.parentNode.parentNode.querySelector(".cpnPodHeaderMain h1");null==p&&(p=h.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode.querySelector(".cpnPodHeaderMain h1"));p=p.innerHTML.toLowerCase().replace(/^\s+|\s+$/g,"").replace("alternative ","");if(k==e&&0==p.indexOf(g.toLowerCase())){d=h.getAttribute("data-nav");break}}d&&(b=h,a=a.replace(/DATA_NAV=([^;]+)/,"DATA_NAV="+d+"#"))}if(!b)throw Error(bfMisc.errorMessages.ERR_BET_NOT_EXISTS);this.bet.betlink=
a;return this.bet.betlink},get_leg:function(){this.bet.leg=this.parent.bet.leg;return this.bet.leg},get_handicap:function(){this.bet.handicap=this.parent.bet.handicap;return this.bet.handicap},get_decimalOdd:function(){var a=this.get_betID();if(a=this.doc.querySelector(this.parent.c(a))){var c=a.querySelector(".Odds").innerHTML.replace("&nbsp;",""),b=c.match("([0-9]+)/([0-9]+)"),c=b?bfMisc.Ud("frac",b[1],b[2]):0<=c.indexOf("+")||0<=c.indexOf("-")?bfMisc.Ud("us",c):bfMisc.Ud("dec",c);for(attr in c)this.bet[attr]=
c[attr];if(b=a.getAttribute("data-nav").match("o=([0-9]+)/([0-9]+)\\|"))this.bet.oddUp=parseFloat(b[1]),this.bet.oddDown=parseFloat(b[2]),this.bet.notScraped&=4294967293}},get_pagelink:function(){this.bet.pagelink=this.parent.bet.pagelink;return this.bet.pagelink},get_players:function(){var a=null,c=null,b=this.doc.querySelector("#HeaderTitle #breadcrumbFixture");b&&(b=b.textContent.trim().replace(/\t|\n/g,"").replace(/^\s+|\s+$/g,"").match("(.*) (vs|v|@) (.*)"))&&(a=b[1],c=b[3]);16==(this.parent.bet.gameMiscInfo&
16)&&(b=a,a=c,c=b);this.bet.player1=bfMisc.ae(a);this.bet.player2=bfMisc.ae(c)},get_kickoff:function(){var a=null,c=null,b=0,d=1,e=this.doc.querySelector("#FixtureData .secondaryHeaderCell");if(e){try{xmlhttp=new XMLHttpRequest;xmlhttp.open("GET","https://mobile.bet365.com/he/Authenticated/Account/UpdateDetails/Preferences/",!1);xmlhttp.send();var g=xmlhttp.responseText.replace(/\n|\t/g,"").match(RegExp('<option selected="selected"[^>]+>[^<>]+</option>',"g"))}catch(f){}if(g)if(c=g[1].match(">([^<>]+)</option>")[1],
"UK"==c)b=0,d=1;else if("ET"==c)b=-5,d=1;else if("PT"==c)b=-8,d=1;else if("CET"==c)d=b=1;else if("CT"==c)b=-6,d=1;else if("MT"==c)b=-7,d=1;else if("GMT"==c)d=b=0;else if("EET"==c)b=2,d=1;else if("POR"==c)b=0,d=1;else if(g=c.match("GMT([0-9\\.\\+\\-]+)"))b=parseFloat(g[1]),d=0;c=e.innerHTML}c&&null!=b&&(e=moment(c,"DD MMM HH:mm","en"),e.isValid()&&(e.year((new Date).getFullYear()),e.isDST()&&1==d&&(b+=1),bfMisc.mc(e,null,b),bfMisc.nc(e),a=bfMisc.Ic(e.toDate())));return this.bet.kickoff=a},get_betID:function(){var a=
{},c=this.bet.betlink||this.parent.bet.betlink,b=c.match("f=(.+?)#"),d=c.match("fp=(.+?)#"),e=c.match("ln=(.+?)#"),c=c.match("Inc=(.+?)#");b&&(a.f=b[1]);d&&(a.fp=d[1]);e&&(a.ln=e[1]);c&&(a.Inc=c[1]);return a}},betSlipParser:{get_market:function(){var a=null,c=this.parent.bet.betlink.match("ORIG_MARKET_NAME=([^;]+)")[1].replace(/^\s+|\s+$/g,"").replace("Alternative ","");if(c===this.b.querySelector(".fullSlipMode").textContent.trim().replace("Alternative ","")||c==="Additional "+this.b.querySelector(".fullSlipMode").textContent.trim())a=
this.parent.bet.market;this.a.market=a},get_leg:function(){var a=null,c=this.a.market,b=bfMisc.Nc(this.a.player1),d=bfMisc.Nc(this.a.player2),e=this.b.querySelector(".selectionDescription").textContent.trim();e.match("^Over")?a="BO":e.match(" Over")?e.match(b)?a="B1O":e.match(d)?a="B2O":e.match("^Draw")&&(a="BXO"):e.match("([0-9]+)-([0-9]+)$")?a="B":e.match("^Under")?a="BU":e.match(" Under")?e.match(b)?a="B1U":e.match(d)?a="B2U":e.match("^Draw")&&(a="BXU"):e.match(b+"\\s+- "+b)?a="B1_1":e.match(b+
"\\s+- "+d)?a="B1_2":e.match(b+"\\s+- Draw")?a="B1_X":e.match(d+"\\s+- "+b)?a="B2_1":e.match(d+"\\s+- "+d)?a="B2_2":e.match(d+"\\s+- Draw")?a="B2_X":e.match("^Draw - "+b)?a="BX_1":e.match("^Draw - "+d)?a="BX_2":e.match("^Draw - Draw")?a="BX_X":e.match("Draw")?a=e.match(b)?"B1X":e.match(d)?"BX2":"BX":e.match("to win by [0-9\\.]+\\+ goal")?e.match(b)?a="B1O":e.match(d)&&(a="B2O"):e.match("^[0-9\\.]+ or [0-9\\.]+ goals")?a="BR":e.match("^Tie -")?a="BX":e.match("^Tie$")?a=0<=c.indexOf("1X2")?"BX":"BEQ":
e.match("^1st Half$")?a="BHT":e.match("^2nd Half$")?a="BSH":e.match("\\+ Goals$")?a="BO":e.match("^No Goal")?a=0<=c.indexOf("LTS")?"BX":0<=c.indexOf("FTS")?"BX":"BX0":e.match("to win by [0-9]+\\-[0-9]+ pts$")?e.match(b)?a="B1R":e.match(d)&&(a="B2R"):a=e.match("^Even$")?"BEV":e.match("^Odd$")?"BOD":e.match("^No$")?"BN":e.match("([0-9]+)-([0-9]+)$")?"B":e.match(b+" or "+d)?"B12":e.match(b+" or Tie$")?"B1X":e.match(d+" or Tie$")?"BX2":e.match("^1st Period$")?"BQ1":e.match("^2nd Period$")?"BQ2":e.match("^3rd Period$")?
"BQ3":e.match(b+" - No$")?"B1N":e.match(d+" - No$")?"B2N":e.match(b)?"B1":e.match(d)?"B2":"B";this.a.leg=a},get_handicap:function(){var a=null,c=null;if(0==this.parent.bet.handicap)a=0;else{var b=this.parent.bet.leg,a=this.b.querySelector(".selectionDescription").textContent.replace(/\s/g," ").trim(),d=bfMisc.Nc(this.a.player1),e=bfMisc.Nc(this.a.player2);if((c=this.b.querySelector(".hdCapDisplay"))&&2==c.textContent.trim().split(",").length)var g=parseFloat(c.textContent.trim().split(",")[0]),f=
parseFloat(c.textContent.trim().split(",")[1]),a=a.replace(c.textContent," "+((g+f)/2).toString());(c=a.match("([0-9]+) - ([0-9]+)$"))?a=bfMisc.Vb(c[1]+"-"+c[2]):(c=a.match("([0-9]+)-([0-9]+)$"))?a=a.match(e)?bfMisc.Vb(c[2]+"-"+c[1]):bfMisc.Vb(c[1]+"-"+c[2]):(c=a.match("Over ([0-9\\.]+),([0-9\\.]+)$"))?a=50*(parseFloat(c[1])+parseFloat(c[2])):(c=a.match("Over ([0-9\\.]+)$"))?a=100*parseFloat(c[1]):(c=a.match("^Under ([0-9\\.]+) goal"))?a=100*parseFloat(c[1])-50:(c=a.match("^Over ([0-9\\.]+) goal"))?
a=100*parseFloat(c[1])+50:(c=a.match("Under ([0-9\\.]+),([0-9\\.]+)$"))?a=50*(parseFloat(c[1])+parseFloat(c[2])):(c=a.match("Under ([0-9\\.]+)$"))?a=100*parseFloat(c[1]):(c=a.match("^([0-9]+) Goal"))?a=100*parseFloat(c[1]):(c=a.match("^([0-9]+)\\+ Goal"))?a=100*parseFloat(c[1])-50:(c=a.match("by ([0-9]+) goal"))?a=100*parseFloat(c[1]):(c=a.match("by ([0-9]+)\\+ goal"))?a=100*parseFloat(c[1])-50:(c=a.match(d+" ([\\+\\-\\.0-9]+),([\\+\\-\\.0-9]+)"))||(c=a.match(e+" ([\\+\\-\\.0-9]+),([\\+\\-\\.0-9]+)"))?
a=(100*parseFloat(c[1])+100*parseFloat(c[2]))/2:(c=a.match(d+" \\(([\\+\\-\\.0-9]+)\\)"))||(c=a.match(d+" ([\\+\\-\\.0-9]+)"))?(a=100*parseFloat(c[1]),"B2"==b&&(a*=-1)):(c=a.match(e+" \\(([\\+\\-\\.0-9]+)\\)"))||(c=a.match(e+" ([\\+\\-\\.0-9]+)"))?(a=-100*parseFloat(c[1]),"B2"==b&&(a*=-1)):(c=a.match("^Tie - (.*) ([\\+\\-0-9\\.]+)$"))?(a=100*parseFloat(c[2]),c[1].match(e)&&(a*=-1)):a=(c=a.match("to win by ([0-9\\.]+)\\-([0-9\\.]+) pts$"))?bfMisc.Vb(c[1]+"-"+c[2]):(c=a.match("to win by ([0-9\\.]+)\\+ pts$"))?
100*parseFloat(c[1])-50:(c=a.match("^([0-9]+) or ([0-9]+)"))?bfMisc.Vb(c[1]+"-"+c[2]):(c=a.match("([\\+\\-0-9\\.]+),([\\+\\-0-9\\.]+)$"))?50*(parseFloat(c[1])+parseFloat(c[2])):(c=a.match(" ([0-9\\.\\+\\-]+)$"))?100*parseFloat(c[1]):0}this.a.handicap=a},get_decimalOdd:function(){var a=this.b.querySelector(".odds");if(a){var c={},a=a.innerHTML,c=(c=a.match("([0-9]+)/([0-9]+)"))?bfMisc.Ud("frac",c[1],c[2]):0<=a.indexOf("+")||0<=a.indexOf("-")?bfMisc.Ud("us",a):bfMisc.Ud("dec",a);for(attr in c)this.a[attr]=
c[attr];this.e&&(c=this.e.match("o=([0-9]+)/([0-9]+)"))&&(this.a.oddUp=parseFloat(c[1]),this.a.oddDown=parseFloat(c[2]),this.a.notScraped&=4294967293)}},get_players:function(){var a=null,c=null,b=this.b.querySelectorAll(".fullSlipMode")[1].textContent.match("(.*) (?:v|vs|@) (.*)");b&&(a=b[1],c=b[2]);16==(this.parent.bet.gameMiscInfo&16)&&(b=a,a=c,c=b);this.a.player1=bfMisc.ae(a);this.a.player2=bfMisc.ae(c)},get_mainTag:function(){var a=-1,c=this.parent.g(this.doc,this.betID);c&&(a=c.index,this.e=
c.str);return(a=0<=a?this.doc.querySelector("#bsDiv .single-section [data-item-type=single][data-item-id*='"+a+"']"):this.doc.querySelector(".standardBet"))?a:null}},betMarketToString:{FT_1X2:["1X2"],FT_AH:["HDP"],FT_OU:["O/U-OU","TOTAL POINTS-OU","GOALS OVER/UNDER"],HT_AH:["1H HDP"],HT_OU:["1H O/U-OU","1H TOTAL POINTS-OU"],HT_1X2:["HALF TIME RESULT"],FT_ML:["Money Line"],Q1_AH:["1Q HDP"],Q1_OU:["1Q TOTAL POINTS-OU"],Q1_ML:["1Q Money Line"]},i:{FT_1X2:["1X2"],FT_AH:["Handicap"],FT_OU:["Total","Total Points"],
HT_AH:["1H Handicap"],HT_OU:["1H Total","1H Total Points"],FT_ML:["Money Line"],Q1_AH:["1Q Handicap"],Q1_OU:["1Q Total Points"],Q1_ML:["1Q Money Line"]}};
