window.handlerbetfair={bookieName:"betfair",fileName:"betfair.js",objName:"handlerbetfair",URLmatchstring:"betfair.com/exchange",bookieURL:"http://www.betfair.com/exchange/",checkBetSlipAddedInterval:300,checkBetSlipAddedMaxCounter:20,checkBetSlipClearedInterval:300,checkBetSlipClearedMaxCounter:20,checkPageLoadedInterval:300,checkPageLoadedMaxCounter:50,bet:null,username:"",password:"",mainPageLoadCounter:1,loginPageLoadCounter:1,betPageLoadCounter:1,loginNavigationPageLoadCounter:0,balancePageLoadCounter:0,
checkAreWeOnBookiesPage:function(a){return a.domain&&0<=a.domain.toString().indexOf("betfair.com")?!0:!1},checkAreWeOnBetPage:function(a){var c=JSON.parse(this.bet.betlink).ORIG_MARKETID;return a&&0<=a.URL.toString().indexOf(c)&&-1==a.body.innerHTML.toString().indexOf("The page you requested could not be found")?!0:!1},boolIsPageFinishedLoading:function(a,c){return a&&"complete"==a.readyState&&(a.querySelector(".pref-show-toggle")||a.getElementById("loginMessage")||("mainreused"==c||"beforeBalance"==
c)&&a.querySelector(".sports-header-container .title")||this.b(a)&&a.querySelector(".sports-header-container .title"))?!0:!1},navigateBetPage:function(){var a="http://www.betfair.com/exchange/football/market?id=",c=JSON.parse(this.bet.betlink).ORIG_MARKETID;return{url:a+c}},addBetSlip:function(a){return a&&(a=this.b(a))?(a.click(),!0):!1},checkBetSlipAdded:function(a){return a&&(bet=a.querySelector(".bet-runner-name"))&&bet.innerHTML.trim()==JSON.parse(this.bet.betlink).BETSLIP_LEG_NAME?!0:!1},clearBetSlip:function(a){return a&&
(a=a.querySelector("button.betslip-cancel-btn"))?(a.click(),!0):!1},checkBetSlipCleared:function(a){return a&&a.querySelector(".empty-betslip")?!0:!1},getBetData:function(a){try{this.parser.doc=a;this.parser.parent=this;this.parser.bet={};this.parser.e();this.parser.get_bookieName();this.parser.get_betlink();this.parser.get_players();this.parser.get_market();this.parser.get_leg();this.parser.get_handicap();this.parser.get_decimalOdd();this.parser.get_kickoff();var c=this.parser.get_betID();return{bet:this.parser.bet,
betID:c}}catch(b){return{error:b.message,Z:b.stack}}},getBetSlipData:function(a,c){try{return this.betSlipParser.parent=this,this.betSlipParser.doc=a,this.betSlipParser.a={},this.betSlipParser.betID=c,this.betSlipParser.get_players(),this.betSlipParser.get_market(),this.betSlipParser.get_leg(),this.betSlipParser.get_handicap(),this.betSlipParser.get_decimalOdd(),{bet:this.betSlipParser.a}}catch(b){return{error:b.message,Z:b.stack}}},clickLogin:function(a){if(a){var c=a.getElementById("ssc-lis");null==
c&&(c=a.querySelector(".login-submit"));if(c)return c.click(),!0}return!1},isLoggedIn:function(a){return a&&a.querySelector("[class*='-label-Deposit']")?!0:!1},fillLoginForms:function(a,c,b){try{if(a&&c&&b){if(!c.match(".+"))throw Error("Invalid username");if(!b.match(".+"))throw Error("Invalid password");var d=a.getElementById("ssc-liu"),e=a.getElementById("ssc-lipw");null==d&&(d=a.querySelector(".input-username"));null==e&&(e=a.querySelector(".input-password"));d.value=c;e.value=b;return!0}return{error:"Cannot fill login information"}}catch(g){return{error:g.message,
Z:g.stack}}},getBalance:function(a,c,b){var d=null,e=null,g=null;xmlhttp=new XMLHttpRequest;xmlhttp.open("GET","http://www.betfair.com/exchange/wallet?isAjax=true&alt=json&ts="+(new Date).getTime(),!1);xmlhttp.onreadystatechange=function(){if(4==xmlhttp.readyState){try{g=JSON.parse(xmlhttp.response).TOTAL.walletBalance.replace(/,/g,"");var a=g.match("[0-9\\.]+");a&&(d=parseFloat(a[0]));8364===g.charCodeAt(0)?e="EUR":163===g.charCodeAt(0)?e="GBP":36===g.charCodeAt(0)&&(e="USD")}catch(c){}b({balance:d,
currency:e,currencyStr:g})}};xmlhttp.send();return"_use_callback"},getMinMaxStake:function(a,c){var b=null,d=a.querySelector("button[id*='"+this.f(c)+"'] span.size");d&&(b=d.innerHTML.replace(/[^0-9]+/g,""),b=parseFloat(b));return{minStake:null,maxStake:b}},setAmount:function(a,c,b){return a&&(c=a.querySelector("input.size-input"))?(c.focus(),c.value=b,a=a.createEvent("HTMLEvents"),a.initEvent("change",!1,!0),c.dispatchEvent(a),c.blur(),!0):!1},getTotalAmountSet:function(a){if(a){var c=a.querySelector(".bet-profit:not(.ng-hide)"),
b=a.querySelector("input.size-input"),d=a.querySelector("input.price-input");a=a.querySelector(".liability-value");if(c&&b&&d&&a){c=parseFloat(a.innerHTML.replace(/[^0-9\\.]/g,""));a=0;var e,b=parseFloat(b.value),d=parseFloat(d.value);e=0+b;a=0!==this.bet.leg.indexOf("B")?a+(d-1)*b:a+b;return 0.01>a-c?e:0}}return null},checkBet:function(a){if(a){var c=a.getElementById("confirmation");if((a=a.querySelector("input[name='placeBets']"))&&c)return c.checked=!1,a.click(),!0}return!1},checkBetPlaced:function(a){return a?
!0:!1},f:function(a){a=a.split("-");return"sel"+a[2]+"-"+a[3]+"-"+a[4]+"-"+("B"==a[1]?"back":"lay")+"-0"},b:function(a){var c=JSON.parse(this.bet.betlink).ORIG_BETID,b=0===this.bet.leg.indexOf("B")?"back":"lay";a=a.querySelectorAll("button[bet-selection-id='"+c+"'][bet-type='"+b+"'] .price");return 0<a.length?(b="back"==b?a[0]:a[a.length-1],b=b.parentNode):null},parser:{e:function(){if(0<this.doc.getElementsByClassName("suspended").length)throw Error(bfMisc.errorMessages.ERR_BET_SUSPENDED);},get_bookieName:function(){this.bet.bookieName=
this.parent.bet.bookieName;return this.bet.bookieName},get_market:function(){var a=null,c=JSON.parse(this.parent.bet.betlink).ORIG_MARKETID;0<=this.doc.URL.indexOf(c)&&(a=this.parent.bet.market);this.bet.market=a;return this.bet.market},get_betlink:function(){var a=null,a=this.parent.bet.betlink;this.bet.betlink=a;return this.bet.betlink},get_leg:function(){this.bet.leg=this.parent.bet.leg;return this.bet.leg},get_handicap:function(){this.bet.handicap=this.parent.bet.handicap;return this.bet.handicap},
get_decimalOdd:function(){var a=this.parent.b(this.doc).querySelector(".price").innerHTML.trim(),a=parseFloat(a);isNaN(a)&&(a=0);a=bfMisc.Ud("dec",a);for(attr in a)this.bet[attr]=a[attr]},get_pagelink:function(){this.bet.pagelink=this.parent.bet.pagelink;return this.bet.pagelink},get_players:function(){var a=null,c=null,b=this.doc.querySelector(".sports-header-container").textContent.trim();0<=b.indexOf(this.parent.bet.player1)&&(a=this.parent.bet.player1);0<=b.indexOf(this.parent.bet.player2)&&(c=
this.parent.bet.player2);this.bet.player1=bfMisc.ae(a);this.bet.player2=bfMisc.ae(c)},get_kickoff:function(){var a=null,c=this.doc.querySelector(".date").innerHTML;if(c){var b=null;if(c.match("Starting soon"))c=moment(),bfMisc.mc(c),c=c.toDate().getTime(),b=(new Date(parseFloat(this.parent.bet.kickoff))).getTime(),108E5>b-c&&(a=b);else if(b=c.match("Starting in ([0-9]+)"+String.fromCharCode(8242)))var d=moment().subtract("minutes",parseFloat(b[1]));else c+=" "+(new Date).getFullYear(),d=moment(c,
"DD MMM HHa YYYY","en");d&&d.isValid()&&(bfMisc.mc(d),bfMisc.nc(d),a=bfMisc.Ic(d.toDate()))}return this.bet.kickoff=a},get_betID:function(){var a=null,a=0===this.parent.bet.leg.indexOf("B")?"B":"L",c=JSON.parse(this.parent.bet.betlink).ORIG_BETID,b=JSON.parse(this.parent.bet.betlink).ORIG_MARKETID,d="0";0<=this.parent.bet.market.indexOf("_AH")&&(d=(this.parent.bet.handicap/100).toString().replace(".","_").replace("-","N"));return a="bet-"+a+"-"+b.replace(".","_")+"-"+c+"-"+d+"-LM-0"},get_parentNode:function(a,
c,b){if(!a)return null;for(a=a.parentNode;null!=a&&a.tagName;){if(a.tagName.toLowerCase()==c&&(a.className==b||a.className==b+" "||a.className==" "+b))return a;a=a.parentNode}return null}},betSlipParser:{get_market:function(){market=this.parent.bet.market;this.a.market=market},get_leg:function(){var a=null,c=this.doc.querySelector(".bet-runner-name").innerHTML,b=JSON.parse(this.parent.bet.betlink).BETSLIP_LEG_NAME;0<=c.indexOf(b)&&(a=this.parent.bet.leg);this.a.leg=a},get_handicap:function(){var a=
null,c,a=parseFloat(this.betID.split("-")[4].replace("N","-").replace("_",".")),b=this.doc.querySelector(".bet-runner-name").innerHTML.trim(),d=bfMisc.Nc(this.parent.bet.player1),e=bfMisc.Nc(this.parent.bet.player2);0!=a?a*=100:(c=b.match("(?:Under|Over) ([0-9\\.]+) Goals"))?a=100*parseFloat(c[1]):(c=b.match("(?:Under|Over) ([0-9\\.]+) Corners"))?a=100*parseFloat(c[1]):(c=b.match("^([0-9]+) \\- ([0-9]+) Minutes$"))?a=bfMisc.Vb(parseFloat(c[1])-1+"-"+(parseFloat(c[2])-0.41)):(c=b.match("^([0-9]+) \\- Full Time$"))?
a=100*parseFloat(c[1])-141:(c=b.match(" by ([0-9]+)\\+?$"))?a=100*parseFloat(c[1]):(c="".match(d+" ([\\+|\\-][0-9]+)$"))?(a=100*parseFloat(c[1]),b.match(e)&&(a*=-1)):(c="".match(e+" ([\\+|\\-][0-9]+)$"))?(a=-100*parseFloat(c[1]),b.match(e)&&(a*=-1)):a=(c=b.match("^([0-9]+) \\- ([0-9]+)$"))?bfMisc.Vb(c[0]):a;this.a.handicap=a},get_decimalOdd:function(){var a=null,a=this.doc.querySelector(".bet input").value,a=parseFloat(a);null!=a&&(isNaN(a)&&(a=0),oddObj=bfMisc.Ud("dec",a));for(attr in oddObj)this.a[attr]=
oddObj[attr]},get_players:function(){var a=this.parent.bet.player2;this.a.player1=bfMisc.ae(this.parent.bet.player1).replace(/^\s+|\s+$/g,"");this.a.player2=bfMisc.ae(a).replace(/^\s+|\s+$/g,"")},get_mainTag:function(){this.c=null;var a="event-";0==this.betID.indexOf("bet-L")?a+="L-":0==this.betID.indexOf("bet-B")&&(a+="B-");a+=JSON.parse(this.parent.bet.pagelink).ORIG_EVENTID;a=this.doc.getElementById(a);a.querySelector("#"+this.betID)&&(this.c=a);return this.c}},betMarketToString:{FT_ML:["Moneyline"],
FT_OU:["Over/Under [0-9\\.]+ Goals"]}};
